### ISSUE TITLE
Port u-boot code to 2020.10

### ISSUE THREAD

**Issue by libv** [FOSDEM/video-hardware#17]
The upcoming u-boot version is 2020.10, we are at 2019.07. Forward port our changes.

**Comment by libv** [comment]
Done with master, waiting for actual 2020.10 release for push to repo.

**Comment by UweBonnes** [comment]
Forward port means upstream changes? Please, not so tense.

**Comment by libv** [comment]
Yes, moving to upstream versions, and we are at a good time, as new upstream releases of both u-boot and linux will happen in the next 2 weeks. Then we can sit back for another while :)

**Comment by libv** [comment]
u-boot v2020.10 was released, changes were pushed to https://github.com/libv/fosdem-video-u-boot
I have renamed our old version to v2019.07-fosdem.
I have pushed a cleaner patchset to v2020.10-fosdem and master.
