### ISSUE TITLE
verify mic-in adc

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video-hardware#3]
* adc= analog/digital converter
* Connect analog audio in source to GPIO pins. TODO which pins?
* Try to verify the analog input:
 * How do we get to the digitised audio?
 * Do we get anything at all?
 * Is the quality sufficient?

**Comment by libv** [comment]
Works out of the box, with the right mixer settings. ADC was tested on banana-pi, which has a mic on board, and tested with a A20-Olinuxino-Micro which comes with both a headphone and a microphone socket on board. Quality depends on the microphone. Alsa can be used to capture this. There is even a project to capture with alsa, and to send it over the internet as Opus, and then play it back: 	http://www.pogo.org.uk/~mark/trx.git We can expand on that, and then, when a buffer is no longer needed by Opus, we can AAC it with the timestamp, and then have libavformat mux it in with our h.264 stream.
