### ISSUE TITLE
Audio noise from HDMI input ?

### ISSUE THREAD

**Issue by rzr** [FOSDEM/video-hardware#5]
Hi,
I noticed that in some rooms (embedded, mozilla) some laptops are generating a terrible audio noise from their  HDMI output...

I am trying to get the reference of those buggy laptops if it can help

Relate-to: https://twitter.com/RzrFreeFr/status/1224294047667408896

**Comment by rzr** [comment]
He faced issues:
https://twitter.com/Mte90Net/status/1224377756571635713

I am hunting for others :)

Please RT:

https://mastodon.social/@rzr/103595126575031870

https://twitter.com/RzrFreeFr/status/1224321912190488576

**Comment by rzr** [comment]
Is this the right place to report this issue or maybe I should contact @libv

Anyway thanks you for this project it looks so good

https://libv.livejournal.com/28438.html

https://fosdem.org/2020/schedule/event/videobox/

**Comment by leon-anavi** [comment]
Hi,

I had an issue with the mic during the rehearsal as a speaker at the "Embedded, Mobile and Automotive. After switching and using another mic the talk went smooth. I guess it might be related to noise on HDMI . I am using Lenovo T480S with Ubuntu 18.04.3 LTS and Linux kernel:
```
Linux leon-ThinkPad-T480s 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Best regards,
Leon

**Comment by krokodilerian** [comment]
If If you can note the room you were in, that'll also help, as there are some rooms with known electrical problems, which would contribute to that. Also, if anyone had disconnected their power supply and still had noise, it'd be very interesting (as a lot of times just working on battery resolves the issue).

**Comment by rzr** [comment]
I am unsure this is the same issue that I obseved with @mte90 laptop:

the noise appeared when laptop was plugged into hdmi and stopped when unpluged.

**Comment by leon-anavi** [comment]
Hi @krokodilerian,

I was at UD2.218A. 

Thanks,
Leon

**Comment by Mte90** [comment]
Yes exactly, there was this kind of electronic noise, it is strange because I use this laptop since years as speaker at fosdem without issues.
I don't know if it is a problem with my linux kernel running on that.

Let me know I can help, about laptop info or testing

**Comment by libv** [comment]
This has little to do with the new video hardware we are developing.

Then, audio is transmitted as a digital signal inside the blanking area of the display signal. HDMI noise is a bit hard to explain.

But having said that, i noticed noise coming from the loudspeakers in a K devroom when attaching the camera to the front desk panel (while testing a camera with a wonky hdmi connector).

Was the laptop's mixer set to pass a microphone or similar input through to hdmi, and then feeding back the introduced noise?

Anyway, not an issue for here, please mail video@fosdem.org.
